### ISSUE TITLE
how to launch ellipseMinimal

### ISSUE THREAD

**Issue by HarryTutle** [SBG-Systems/sbgECom#7]
Hello, i have some knowledges on python but not a lot on C, only on Arduino little projects but that's all. I need to use an ellipse gyro for a data collection project, so my question will maybe stupid but i can't manage to read something when i use the command 'ellipseMinimal COM4 115200', even if i've installed the static library just before. Do i have to compile something before ? Or is there any command to write before this one ? Thanks a lot for your answer.

**Comment by rsiryani** [comment]
I close this issue as the support team was able to help you on our dedicated help-desk.
Feel free to get back to us if you still have questions.
